version: '3.5'
services:
            
  service-app1:
    image: app1:0.0.1
    environment:
      - DD_AGENT_HOST=service-datadog
      - DD_TRACE_AGENT_PORT=8126
    ports:
      - 6001:8080
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app2:
    image: app2:0.0.1
    ports:
      - 6002:8080
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app3:
    image: app3:0.0.1
    ports:
      - 6003:8080
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-datadog:
    image: datadog/agent:latest
    ports:
      - 8126:8126/tcp
    environment:
      - DD_API_KEY=9f18f0cb40551025332a86768b248f44
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:datadog-agent"
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure


  haproxy:
    ports:
      - "80:80"
    image: haproxy-app:0.0.1
    deploy:
      mode: global
      update_config:
        parallelism: 1
